spring:
  application:
    name: KotlinWeb

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/beriholic
    username: beri
    password: 123456

jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR
  client:
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: My Web Service
          description: |
            Restore the DTO explosion that was 
            eliminated by server-side developers
          version: 1.0
    ts:
      path: /ts.zip


sa-token:
  token-name: token
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: simple-uuid
  is-log: true

server:
  port: 8080